name: ci-app

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'pull_request'
    steps:
      - name: set up go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache-dependency-path: go.sum
        id: go
      - name: Setup Golang caches
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/go/go/pkg/mod
            /home/runner/go/bin
          key: ${{ runner.os }}-golang-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: checkout
        uses: actions/checkout@v4
      - name: download dependencies
        run: go mod download
      - name: make all
        run: make
